export const couple = {
  groom: {
    fullName: "Mohammed Sameer Kallangadan",
    firstName: "Mohammed Sameer",
    lastName: "Kallangadan",
    shortName: "Sameer",
    relation: "S/o",
    father: "Abdulla Kallangadan",
    mother: "Ramlath OP",
    parents: "Abdulla Kallangadan & Ramlath OP",
    address: "Kallangadan House, Perinthalmanna",
  },
  bride: {
    fullName: "Nihala Jasmin KK",
    firstName: "Nihala Jasmin",
    lastName: "KK",
    shortName: "Nihala",
    relation: "D/o",
    father: "Abdul Azeez",
    mother: "Rasiya EP",
    parents: "Abdul Azeez & Rasiya EP",
    address: "Karukulam (H), Puliyanamkunnu (P.O), Chalavara via, Palakkad dist - 679505",
  },
  coupleName: "Sameer & Nihala",
  monogram: "S&N",
} as const;
